### ISSUE TITLE
Avoid reloading cordova app when clicking a push notification

### ISSUE THREAD

**Issue by sarbona** [pushbots/phonegap#69]
I am using plugin 1.4.7 for android and when I click a push in the notification bar, the cordova app reload again.

That happens even when the app is in foreground. That is a big problem, because if the user is introducing data in the app, he will lose all the data if the cordova app is reloaded again.

Can we avoid reloading the cordova app? 

We need to handle the clicked push with the "notification:clicked" and give the user the option to save changes before changing to another app content.

**Comment by AbdullahDiaa** [comment]
solved in 1.4.8

**Comment by sarbona** [comment]
Hi Abdullah,

I have updated the plugin to 1.4.8, and in the first rebuild of the app, 
the build has failed because the new plugin needs min SDK to be 15 and 
we had 14.

That change is acceptable, but after updating the min sdk, the build 
fails compiling the PushbotsPlugin.java file in line 79:

Pushbots.sharedInstance().idsCallback(new Pushbots.idHandler() {

The compiler cannot resolve the "idsCallback" and the "idHandler".

It doesn't seem a problem with SDK versions, because the methods not 
found are in the Pushbots class and they should be defined in your lib:

<framework src="com.pushbots:pushbots-lib:3.0.4@aar" />

What can I do?

Thank you.

**Comment by sarbona** [comment]
This issue is not solved. Tested in 1.4.9. The problem remains. 

When clicking the push in the notification area, the log shows this:

D/PB3: action=com.pushbots.MSG_OPEN
D/PB3: APPID:xxxxxxxxxxxxxxxxxxxxxxxxxx (hidden)
I/PB3: POST 2/pushOpened
I/PB3: Params: {"date":"2018-02-05T17:39+0000", ... }
D/AppTracker: App Event: stop
D/SystemWebViewEngine: CordovaWebView is running on device made by: OnePlus
D/AppTracker: App Event: start
[INFO:CONSOLE(1)] "app starting in ap js"
