### ISSUE TITLE
getRegistrationId callback never called

### ISSUE THREAD

**Issue by sarbona** [pushbots/phonegap#70]
I am using plugin 1.4.7 for android, and when calling the getRegistrationId nothing happens.

I have tried debugging what is happening, and when executing this:

window.plugins.PushbotsPlugin.getRegistrationId(function(token){ console.log("token received:" + token); });

The console is only showing:

PB3: execute: action=getRegistrationId
INFO:CONSOLE(73): "cTEJveMITb...", source: file:///android_asset/www/plugins/pushbots-cordova-plugin/www/pushbots.js (73)

Looking at pushbots.js I can see that the response for the getRegistrationId is not handled correctly and it is falling with the unhandled case in line 73:

console.log(data);

But the getRegistrationId is never called.

**Comment by AbdullahDiaa** [comment]
solved in 1.4.8

**Comment by sarbona** [comment]
This issue is not solved. Tested in 1.4.9. 

The same exact problem remains.
